/**
 * icons.js — the Windows 95 shell icons this desktop uses, inlined.
 *
 * The project ships no binary assets: every other surface in the scene is
 * painted on a canvas at runtime. Icons are the one thing that genuinely
 * cannot be — they are hand-pixelled 32x32 bitmaps, and anything drawn
 * procedurally reads as a modern imitation instantly. So they travel as base64
 * PNGs in this module rather than as files: no fetch, no load order, no
 * file:// problems, and the "no binary assets" property survives intact.
 *
 * Each entry is [32px, 16px]. Both are REAL frames out of the original .ico,
 * not one resampled from the other — Windows shipped separately drawn 16px
 * art, and downscaling the 32 loses the pixels that make it legible small.
 *
 * Generated from .claude/skills/win95-ui/icons/ico/ via tools/ico2png.py.
 * Total payload: ~12KB.
 */

const DATA = {
  'computer-system': [
    'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABCElEQVR42sXXCw7CIAwGYI7O0bhZ3SZEoG8YFdNETeT/1rENU1JGzhn6SlGjBZZShjoO4YI5CFfL4dSwQF7pVAPMk4VBesD1EU26C3EDrm+eWoHcv5/XyndOFwBq2SF9GLEwVwEyhLoq3geADDkHAAIAI+R8B+q5xp2AAEANvN/hcAjqAHnkIYCMAadPAb555BFyugPtDoZvLBzEBjAf/a/9VogOUMPnR7EPIgPaHK4HkRfCAYgugGsvYIVYF6F4OoZLsL68EAkw/VYB5PSUtjPqIVzrqce0tBTQkVHFQaRg1xWxAtGCvQA3xLFdX9qyqxBj8PYfGhZyOliFRAWzkOhgEvKP4O3xAb/fcPkcezhRAAAAAElFTkSuQmCC',
    'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAiElEQVR42p2TAQ6AMAgDeTpP28/mYlLtsJ1TEjJj6MFIF1EiMztn7AYErbUpt4AQIioEIJwWgC4KNMqmbwkY/0fmmQBRV77GAtD7BeKp9gEE+Q8ID3iIAZiXpAFWjGWhSPnATqA8wCDufl+VINV9CsQ1bg+P0auZip3tG7E7eF2mA30VStBKeACv9qzsDY2w5wAAAABJRU5ErkJggg==',
  ],
  'folder-open-documents': [
    'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAuElEQVR42u2WSw6AIAxEe3SOxs0qDZAgqdH+ZNNJGuMC5tkBBCCVMqqUgkfNa60EgEfMp8IhyGyvXWEQu9n+3jzjIKYZTdysHs05iLVbDl//bs5B0Lg+VtmVafrV/AliAKB40dEk2rrHIQDgVrhGMNqxLEwUHS7UOssTljxEu6N3AMwQY/WfhWBigF9jWM4BOYBHB1S7ICIGNYBXDOIIImJQ/aQ8Y1ADOMeguYiAS1nuCehUqVSK1QVWtEy+O8QqBwAAAABJRU5ErkJggg==',
    'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAeUlEQVR42s2SUQrAMAhDPbpH683cOqh1WbQr7GMBkTHymmpFvpSqWqzwy16ZUQPUVUKmWay15h2hHULSTUBmPn0PyC0RJmBmhDgAB7cqgPDhMc3Y5te9vrMBsj5OdfNqC2wr4f5WbiHrdAs7EEiRP+OqKCC8+Z36gQ7rEbzQky4cmAAAAABJRU5ErkJggg==',
  ],
  'folder-closed': [
    'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAcklEQVR42u2WSwoAMQhDPXqO5s0swtCBlqGfsXWTQJBuNLy6UIRqBMBGPjp8RkdCvMPFVHVYQ0OsDg8N4U282a5nduZjj2zp36P1BLBt/H8r0AS4OdxrF4AESIAESIAESIAESCCVgD8yXA/TeiDeN5WvAtnF8RFmzDMbAAAAAElFTkSuQmCC',
    'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAATElEQVR42mNgoBZoaGj4j45J0nzgwIH///8zoNBEGYJLM7IheF0H4pAKoAb8RzOAAa9LkGmsBhCrGSlsRl1AVReQg+EGQMF/MvEgAAAHeeYQ8TK23AAAAABJRU5ErkJggg==',
  ],
  'folder-programs': [
    'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAA4ElEQVR42u2VWQ7DIAxEffQ5Wm5GQzAtEBaDA60qJhpF4cN+TFiItrYKAmBqnt7ciYqeBmELH8ch8pSEPrPX6Sxl1PHbWY6+ARqD8ACa5m6NKAF+KoHWlpRaBJRLoGdn1NwFkCbgCqBpvwPSdzdALgEJADe5+ZEElv6CXAIaPZLAUoBqAmch8ALjz/xxDBoBcKdY7ACA+DYMAXg4BbEAHkIMwIpWcAgA7pQmYB2mdDW3D5khgOwV7QuFzUHgMVxOZz+aQBFg+iJsAYRn+zsFwdj/JPBVgCVHsWRbKr21FekF6GuRVIc+BI4AAAAASUVORK5CYII=',
    'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAgklEQVR42p2SCQ4AIQgD+3Se5s9YNB6ISmCbNIaIYz2ALiJia0RVm0spzIxtDEFeizXETVeLrDqADQBuEj1eAXoy6gaxCcadRLwBbALJ5tpN8AugE0R0HEEnWBKgNM0KD4B1e+vajQUASbOCTEDXKLYEevcJIVwB6Z/pAlL/4CLO+AOw11i/0EcPZgAAAABJRU5ErkJggg==',
  ],
  'audio-cd': [
    'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABOklEQVR42s2XAQ7DIAhFPXqP1puxtAWLCAKzq6MhWbbpfwKiLcU2QF9msBoCFF8O8CoIDGBeByj/ANB8v20baP503htDgVMIoFTf9736DAwcpgGISQH/qQJwz6ZMDqqhLvWBFIAAyW+7Ki5/Q+koAItsHOIQJ/ouNQmAw7IQd8HhoC41QQAuXusnJd4XZRhAitMOCUHQgHPlXfjvgrQALPFQQXLxppJx0uvz9cgm5ImHICwACcHC2RQumSXupmEEQBDaJLxLjsSnIqCsXgWYakyRFfwcwBNfGgGqcqsIPfGpCPAtJo9eal7TABaEFG8bT7mblgMR7oQZccDGFIFInQeeOIeQABpE+jSMigM7IUYQ6Qsthxif+TYAQXx9m/a2FpcyIWav8rwoo2kQfeIZ00C6CLz0AvPYe+MH5iDbXPH9P4UAAAAASUVORK5CYII=',
    'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAkUlEQVR42p2TSxKAIAxDe3SOxs2qWAqxhI/ixIWYN02hIn1p1e+lqJTSoBNAA6macs5NOxD+QAEuFtU+3pYdoKwI6dnVIDOAmykgbDx2BKB5gJSyX+YQx/fPAf5IrUPkDBDzYgVyEoHltU5Ie0+P0yG0WQAQcowNwMwIQAidm2m3+w0xyGro/DozwKeJxblYGS+Ekty8o9MSFQAAAABJRU5ErkJggg==',
  ],
  'network-neighborhood': [
    'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAzklEQVR42u2W4QqAIAyE9+i+mb7ZSqiwMmvbbfWjxUEEnR/TyREJKqXET0QeVY1rlVKGWgDYDaBZYKf6PRZgfqecN8UDNIv/AKEAr06B4B7wAeiNX0+1E1CItf1PC96F0f4f2+9yDloAWp4VoNd+FwCpPA4iCxVSYQv5AyjDBkMCi+GaZchVfRc2LsZrd+CUHoOwQa3y8efTVig8Rh0Q/Izw+CBAPkkOIPBAhA3zFFjveJMHImyoPRBhw+SBCBsmD0TYMHkgwgbCAxE2VB4TvjwvDni12iAAAAAASUVORK5CYII=',
    'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAZElEQVR42sWSUQ7AIAhDOTpH42bdXIzxw1IxSyTpV7UiDzNS7o5ZVql2ISKGegDKAQZ8uhOwmAGO/l+ew+r1chf9INMZ99RX3OVeDGwvsyYWwPx/ArKJp77iLvdCcd/dC8Wd+g+2+lfna6ntLAAAAABJRU5ErkJggg==',
  ],
  'globe': [
    'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABkklEQVR42sVWCRLCIAzM0/O0/izKkWRJqQekijJF6XSPHJToxsFMcsdTRej5fV51lt/1vwBeRh4JBWxYBlqBdan3EIkSKDv7JFQ1gAM+/C5gXKeT2CUAqjkQiSTaHslxHEZCN9ZIACACq0qBNfWPkmAIxxYBe5gqhauSUPuRRHGBtkJxUjUHR3J6v7lSrrToglqp4FXRRLkuqDycwa1AgHnBAY+to0XwBkZGoinviUhjWVZd3ycgjZkewcXVoxOJBDzzZz0gOuAkeI9ALD8OXfDUiEA5gmMOLBG4Un3qD51AzQNiq4RlAt7/x9jWOSNm+zwQWAfHSggkvPuJN51eegZOGQSogbW4NhJj45ERmHha/0vg0DhMsR0yfR0TbiAyNh/5Gjyc5Z5UAQjB4/vAjvWkB4h1eepEJqCoOgU8hiGc6ZczAEvia+CZyGymA18ReeHET0dOnBff9f9nfTiI5UVYMpNPhr5wlQeprnjWi8QqmM0InNSIZLD8TemdXNhN0o+U350PU1XvXLijN8jC/Gg8ALKGqlmuuDByAAAAAElFTkSuQmCC',
    'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAk0lEQVR42pWRCw6AIAxDe/QejZuhYx/nB2RNloDSZyvARK21DnKMrEmMwZbE2E9BZ+yhm39IMpu/ABlmc5pkSVAhO4Dw4yLIc1oC/x9TAK1CriEJvIKZvwGv3pEAkWAJiJdEgCSy909XOQfIaYXwmh3zE5IO75szJI+DUFXpq6sUJYib/EJLNdTYb8bJ/1iq/8xNB9WRHrRUu/j1AAAAAElFTkSuQmCC',
  ],
  'recycle-bin-full': [
    'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABGElEQVR42r3XDQrDIAwFYI/u0bxZN8oCIbyXH2cUZGBb37dUHRuj0Oacj3Q7NrqaDtVNjyHQX6gotDpeDmaT22v6Hq+lEHoSFKjLHQHQs2mAV075XGtRBENvVYB9S4SQse11IBPoie1KR4EeGr3SFMCDMERmIYYVQQgPwspuG5rrG/ekAQyi72cINscWgEEsgN1vXsE+wIN4oWYx1taBLvWY4+0ozAsNwyOABOsu4xoY9TQAhUXXjgJskFeRYwCN6KhAGI4A9j1Hi7QF4PUrFWCBLQCLQDvDngsZQDocbUd2DlQW4TYAnYJsdxwFoDPelryyC0qAX3sfQj+9VcBOeAi5CUhDugEh5BaAQkhw359XBLkZDCGV4A/snnbxa1VycQAAAABJRU5ErkJggg==',
    'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAgElEQVR42p3QCw7AIAgDUI7O0byZm2YY7Fo1kpC5T58yM1LuXlvjelvxcRSuJRQvc4AhcU8B3EkhebMJKKX0ZpAa643WH6Ag9n8GwBBz683+SRqBAy2IUFvjaSgQgQgpYAqvTpB7CeAp2PUYwFGOge+hHGUXltANQKEbYIJSj3oAeEPae/D8QmcAAAAASUVORK5CYII=',
  ],
  'recycle-bin-empty': [
    'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABBElEQVR42r3XDQrDMAgF4Bw9R+vNOhoqOPeMmqkBKXRb3rf80Y4RaHPOm2p0NR76NH4tg8hQam/g1/1UiBYqhn5dr+talQZB/woVATgiBSLnNgr4G3IyAhriCLKb1xNAGII6QxAJ8CDcEM+8ngJkX08/boBnaloAFsT6vpiCc4AGsULlWgqtA6r14zlWoTDvVg7tBioK5kX3OdBzmLkAKMz6LBUgg3YjkgbgiIoRMMMRQM6ztUhLALtqGQEtsAQgEWhnyHPBA3CHo+2onQORRXgMQKegtjtSAeiMl0Me2QUhwNvgM+DuuM4MNyGdADekGmBCugAqRAkuf5n9eVjtCoaQSPAHAVTPbz8jdMwAAAAASUVORK5CYII=',
    'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAfklEQVR42p2RAQpAIQhDPbpH62b9X7SwpRYNhiHtpSTiSFWrtdwKgSZUnFOQDSLwt2sppfsICl7rFZAUZC9CADCE72wA77WoPwEeRFS6WfQ7PqAFGdTOzvfuAAQQigBLOJvAOgXwFF69BvAq14DRDFc5hUPQC8AFvQAWkPHUBwK+zZrfpl0sAAAAAElFTkSuQmCC',
  ],
  'settings-gear': [
    'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABAklEQVR42u2V4Q7FEAyFPbpH82buFTPHWQnK9kcTkcy0X0/bzZhjx8istV6z/i68GsA5N7W2ALSyDfYKwOW0WOHsVQC0dPYJQHj2iQIpaIKp9cdWBVCJ1ISszDYAa+NqTQcCwDMdQMw2ZJ5ViED2UQqcEnpf9yGKAP52GtWQARA27EsAsmOEkAEweLijBigz87esrRKgUtMAqenSwpq2FfBSD/SDIADKiXuvAtK9bgAcvayCr2UmBmcfKgCpEVs73lEDSJnxyEEAoVwTAPhpxUbkrGpyM9TINDzqWgvO08FnBKD5P5QArAxnOlz3EQB02Ai0FoBKYzoDLQ3e2y/Hjg3bD//LMYu/SWR6AAAAAElFTkSuQmCC',
    'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAjUlEQVR42rWTgQ6AIAhE+XQ+zT+zIZ2eNgrduo2VBa+DVFS17oSIWAzZw1JKOv4FrHZN24A7oa2PASZVacHO0gC/N5C7QTtwZ+86iAEsJBqEAQx+GaL0Vj4c1HCI+BIXAuquEgAvGEW4Ti6iIaKY28GfCWfAQvKwPtYTJNrKvKEeg5PFQfIEzoWkehBdFwidGq0Mr+0wAAAAAElFTkSuQmCC',
  ],
  'find-file': [
    'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAA70lEQVR42u2WWw7EIAhFXbpLc2dOtdD6oA4odJKJNyH9qXK4+HJua4sp732UhjqARAAQfwqgAtHaGkJgAyw5gQmTMKlLARNyAaYg8gAY7ACg/HIgICEV/H5jipS4gzgmw5aU8aQ8jgPQJo+EA/kLLnAXpwigtP/RAUsAqQNtG6iWqDhQnXJWDkh2wbfqpxxAAExGOSCtXgxQHkSj3pusAULdYYJupLOI68QKQOUIVnVOGCsIKweq7XlVjndDA2HqQH25yCBUAc7LRgahDiCFUAGgFtkIov937XU0uOMpiIX3wKRHN8QN8LreqHTrz/QBMrQXW+84UfsAAAAASUVORK5CYII=',
    'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAgklEQVR42pXSYQ7AMAQGUEd3tN6sWxeE4usq8Ws81pbIBTPPUxKKVYBijIGRP8CKFjkBb8meGRDdpnWbJECnk5vWIQlIza6oQkogNYMt4AbafLWBInuzHuqOlID9ilyRgTS/9AgE4r2znEVEILA++qyQFihemmRE2peIwyPXzWlDiwf+s/XJZR/Z4AAAAABJRU5ErkJggg==',
  ],
  'help-book': [
    'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAyklEQVR42u2WUQ6EIAxEOXqPxs3qokG7ja0ttvLDJCT86HsMEillZeVFoAC28ZviHDgcAkQCp8DpSBfR4OkiIhwKIh6jzVNEJHgH8xHayGPtZNVSE8Onxbrnxq1IgMNN/RHfgRe+Q4Xa23tcAt7a78AUXmu1C7DK1JVLYA4fEtgbuKpzCXA4EUCzQH9QFTHC+3a6BWgsIq/hmsCTSAic/uPPkwBgE4mAk/zXbBCJhA+JZMBdIplwk8gXcF1k0uX0FJlyM2YiKytD2QBviibCajWS0QAAAABJRU5ErkJggg==',
    'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAfUlEQVR42qWTUQrAMAhDPXqO1pu5CauVYazrAtIf32s2qEgRCPQ+VE5iMHDPkugRHKclYnBL9IZVxQeQTFLcjAW5hDVgtccYKWy7LmAwq227JvYWsdLux03YxjlvAC6icPwESyYq4Se+MBNFO9glTNSBS9EXOBX9epGdx3MBJ9pUyTFNZxsAAAAASUVORK5CYII=',
  ],
  'document-text': [
    'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAdElEQVR42u1XCQrAIAzz6X1af6YUFnB4TKGVjSUQLFhoSK1iSi3yRe/4GSKSDbZGxFMhSLQkwCtGcVUdi3iNgAigMAUsC6hG6MYZsN/L/4cDPIScArbgSAt2SQfoAB3gRcS3gA58SwBEWJI3l4p3vucRbFAAae0c40N0tNgAAAAASUVORK5CYII=',
    'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAARElEQVR42mNgQID/RNJYwX8QaGhowEtjNQRZklgaqwHEgAMHDtDYAKgkunMHyAXorhl1Ab1cQLYBIAliMa5c+Z8EjAIAc/wzNSUthNwAAAAASUVORK5CYII=',
  ],
  'windows-flag': [
    'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAA00lEQVR42u2W0Q6AIAhF+XT//PYgOC0kNGmtSbsPrhZH8DKJdnwk8AcAOLUcBJO6BYADFA9V/oLOrqyEzTqxwCrv5EmsAQANRgWAogtA/fTaAL3sVlviAGAflOUVOC+gwZwSxAJoMJEAXevdtKUAiAu6lhMXDAC8NwfyJp7NAaLEki5wdZCVUtYIgHsO6MegBahltABTcyAIAMYZwPIK4JpAg2kSRANoMHEAhvXMtlQA4gLdcuICfHQOdG85A3NgPcDAHPDd9ya+986B6Xvkjh076ADz/2PDRlVjyQAAAABJRU5ErkJggg==',
    'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAcElEQVR42q2TQQ7AIAgEfbpP82fTkxWBApqSbLzAhF1Da7VCqVwkepvCYeQQFoICoYcNAN+Ou2YKILGAB/YA8iUPz1pArGsBLEu4NqNfwAA2SO+dqj4BlZoAY2MCxhihJGDTBaD9AVhBn4Z4c3HhKT/+ZnP+bvpsBgAAAABJRU5ErkJggg==',
  ],
  'document-image': [
    'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAxklEQVR42u2XUQ6EIAxEOXqPxs26YcUNlELtbof9YZIJfqh9tKPRlISIiCOdvCoXRakC8F8B3BDRADlnH0Q0QJELAgHgggCFUDMeQFPpxAGAAMgZbwNYhEwF+QpgtqOu0H1M1ROInwDaVRYfACgQYNVu3gKwGEFXvDUEoF3rzckIYegIWGv5x3dGLgeH0MoEDwAtRBiAmIAoDgSYTGDYfd92wHtAHwHhQ2i9iDRAyFPwpLDVvfM9cAAOwCOAchLS1s8Jb/JbL9Cl0n02ubTRAAAAAElFTkSuQmCC',
    'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAb0lEQVR42r2SUQ7AIAhDOTpH42bOZpCZKbPGbST9kfJoVBEvVS2MJCs0Z2VmOYQFoIYQBlBtd60B2iQfAmoji80ngDmGAqAX5BEQixpTl2KawBe7qfggnUDeSHCacRafJ4Z+eMYdABqsOsDowgjJAYrePQYKblTfAAAAAElFTkSuQmCC',
  ],
  'drive-floppy': [
    'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAsklEQVR42u2WYQrAIAiFO3pH62ZujQlRak5rjdGD92Mg+VFODWHrD4oxgsXDkmellECrHHsDwBKAnHgpwPIb2AD/BdBAYNw0AK2nA3DdTwSwttQaAA8vQfCbrYGS7ulVugGsySUAYvDQAHiAVVwyymSctYpLcwkVDkMAap8nX+aepSm+zwP0fkNtsXYBhNVJtAZMBSBtMJJ7fd/9BNoB436CmSaTe/q/cQ1npx+85K2tRgfynptu22IhBQAAAABJRU5ErkJggg==',
    'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAATUlEQVR42mNgGD6goaHhP6kYRfOBAwdIwlAD/oM1kwqQXPCfJNuBOuC24zUA3a+45FEMQAscFIxuGEEXoAOCLiAzCv8jJ4P/ZOBRAAUA+4Zll6VZnyAAAAAASUVORK5CYII=',
  ],
  'drive-hard-disk': [
    'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAdklEQVR42u2VSwrAMAhEc3SP5s3sh9pS202iqIt5MBiyccIYHAMAAADoBBFJpj7NmTlNlwEpa34bOA6ZmAgeA9mvnzLgGbQpA/vNqd+sFmWN9DZgpXgMKK4Z8BAyhGW/QLOLqkszEFlbRfDaAwVbUOwmlmSBPmz6dFFQdO4sEwAAAABJRU5ErkJggg==',
    'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAUUlEQVR42mNgGAVw0NDQ8J9UjKL5wIEDJGGoAf/BmkkFSC5AGECq7ZguAHJQnIYFw7yK1wUQs7AbAFNH0Au4AF4vUBwGZKSB/8jp6D8ZeJAAADJ7kSlB7HdcAAAAAElFTkSuQmCC',
  ],
  'drive-cdrom': [
    'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABPUlEQVR42s2WWxLCMAhFWXqW1p2h1RIJ4dm0Kg4z/ch4T4DcBGAxWmuoJdwZXAgRem7b1vO5jOf1wiRrARgwa+LQf1gCECCr4jZEBPBaWYXYxfsOFgD2OAVB/fYgIgAufpwQLIlTzhAxgBTfv9MQY/ltCAvAEk8NJBcfJlmBkCYUiacgLAAJwcrZ821Q6IqHbfAACML5k6Eal1dA2b0KsGRMmR3cDhCJ/7QCNOXWEEbiSxXgR4xXg9+UpwC0h0UkPhoPqKaVFtemvCKOhzFlIAYAr2efl48tziEkgAYxiXtREUd2Q3gQKkBkOJgYLA+AIKbnmdyhV4lIPKoCHVETwHpiaycj2wbuE6p5cQBpKFZqMFMFjPUuQCU0B/QgUwAgypfNTKtyAA16VgCqkOVjeCVAyv/vSu/2wy/l/8UDJbo/1AdwANEAAAAASUVORK5CYII=',
    'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAh0lEQVR42r2RUQ7AIAhDOTpH82ZsEro1SNSYZZj+wUtbRf4YVTXo6NBMXK21fZAvxSkDoHvFFsd4I6DPFNIBvhAvLEccW7sA4IG8i3sxGIDi4EAqB/xNEAPYtkUvrg5ArjyA8DEiGcfKxWTr2U0cjgAvSyUvDOJOSgfVVM6mBe4of6Ed6Ju5AFMPn5Vm4RAiAAAAAElFTkSuQmCC',
  ],
  'internet-explorer': [
    'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABEUlEQVR42r2Xaw7DIAyDOXqO1ptloxMqFXk4WQAp+zOGv4TZalvbvpjlOiqsfbe9W2Rv6VjnIsbOKRWVICwQCCAjjIK4ACQe+P1kopYEgQFW8S7axf+fhgswRvYIX9dVID4DBMS7sCx+HzbV+7c2BADwE2dLfPlXYRDkiRPSuWobH8IBSHSuQIQAkM6rAMRzZvF+/+SEClIBgCE+LFeTgEGAmqBJAIyue60RS+cAMPFWWc/odQDKuABfMfEQAOCSaQI2QHgKeBrKE0D8rELEMsDu3poCJ8IHAiCW76/KkkoACRs2QAjX9gZYNhRNw3k6NgACIJR4LMcBAG+z7HM0jHx7wVGczkQgOOjEW215Z+b6APXTtAfrqtqUAAAAAElFTkSuQmCC',
    'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAgklEQVR42pWTURIAEQxDe/Qczc2yy4y1laLMhA9eWlpmV4P0ujocQaEJuIarwI3BgN85YeIM0DYAm2AwzgoaXWEXYWdwhPcmMZzRa9Dhusb3PKiCpZQfkG4U+9If0XH/Bj51LRmAJoXFoEdY1Z3rCmi97dBA0kTznclhJJpRUn9ffjxa4UQuCcsXbAAAAABJRU5ErkJggg==',
  ],
  'folder-pictures': [
    'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABcElEQVR42u1WWxLDIAjco3O03IxWDYLEB7bp5KdMiU102GXxBfzNGRHxyt/D+GfgEfsJCQE/juP9xLK9lcQu+K0kUpAU8FOPzJnBPNqr+91WlVMC2C7BN20t3yf1X/nW/NlVYAzKNZEIqZACMyBr0ocm1rU/pMAOWAYEl/9nK2Nq/0CVrgI95hJIPH/LdK9eHlzH2HefwKAEbTbZNc7ZQltKUpZ3IStxfEm8IkMCKZrPUkFbMhk8kUBpU0CJRw4QzDECNmsBQD2E9D39L/U3JO4iwFACBFKpz5YMIMyY0q8E0vcwAV0iJivJ2JGowHlf16WVfvJeQHBZBVMFKgGYuorUoFNiLHY4TcQSgDv0pgpUSYEmQ9/WtXZOXKtAj8ByGTYlyPXrgwqYyEyuHD0CvhzTnVAmkc+wBSs+2jWlP0ygzZQNCBqw0fbsLxyjcyR0FowsChQ5KacK7Pr+0R24D+xcLr6+ET3l9kbND/nfnrcX5SHKRM7UmiAAAAAASUVORK5CYII=',
    'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAlElEQVR42q1Siw6AIAi8T+fT/DMSDQKNZhnbjfE6QQD+EiLiEdXNy8XM4FJK0EskWbEnyeAI3ot1pwT6ogASPOFt391EEArNw9F2pBMBVFuLNQmSJDF0u0JJbwngCyWZzpGqEl/zZwQyV2/xKlSfzt5j9PwHtkKwJTc/Yk66hfHHx81MR+Y7yI7pTgeCr/BnzhvYkwMpEgd2ERUrwgAAAABJRU5ErkJggg==',
  ],
  'notepad-pen': [
    'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAA80lEQVR42s2XAQ6EIAwE+3R+Jj/rhcQebQHxPLbSpJEYzCxbkUpkg89cPZ5HSolLlCtifClEJpZJEqvGAs85j0VsIwARAm4FHPyigALntwQI3AkoE1BZBVT4+a7EOWDhFF0Cv/LAEozhQbtABFTbmcN2QT0TuAMHl0Dg2gULB5egwqmz/w+0AFJgciK+cEwJCnwuwh1K6xwgc9XvgkvEaajhpNyYwFeUQEB65fqesh3RD7S2WzghG5I5fNyQ/FkCbblqOk22x/EyB+xH5up5gAAyn9nnPeGDEnhrf++ItuqKdxMQ05Tu6gDShVvwzu85IrvxAUCwwGus1aFKAAAAAElFTkSuQmCC',
    'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAg0lEQVR42p2TCw6AMAhDOTo3czebQ8KAuE+3JgST2WdRJHJVsA9VRcy87ENIPES7u5/aAYhKKQHQzI15CVDzl0gAcoCWAXSc6wSk5tN30CwBQA5AoovZKkGwBGbWa/H0r7EHZHN4ui/SKnaemf7bOEtgN88XaQPYbyIwwnyRBn/jQSW9RzN3Hn9WVckAAAAASUVORK5CYII=',
  ],
};

/** name -> [Image(32), Image(16)], filled in by load(). */
const cache = {};

let loading = null;

/**
 * Decode every icon. Resolves once they are all usable by drawImage().
 * Idempotent — later callers get the same promise.
 */
export function load() {
  if (loading) return loading;
  const jobs = [];
  for (const [name, [b32, b16]] of Object.entries(DATA)) {
    cache[name] = [null, null];
    [b32, b16].forEach((b64, i) => {
      jobs.push(new Promise((resolve) => {
        const img = new Image();
        // Never reject: a missing icon should cost one glyph, not the desktop.
        img.onload = () => { cache[name][i] = img; resolve(); };
        img.onerror = resolve;
        img.src = 'data:image/png;base64,' + b64;
      }));
    });
  }
  loading = Promise.all(jobs);
  return loading;
}

/**
 * icon('my-computer', 32) -> HTMLImageElement | null
 *
 * Null before load() resolves, and null for an unknown name. Callers draw
 * nothing in that case rather than throwing, which keeps a typo from taking
 * the whole screen down.
 */
export function icon(name, size = 32) {
  const pair = cache[name];
  if (!pair) return null;
  return size <= 16 ? pair[1] : pair[0];
}

export const names = Object.keys(DATA);
